In [1]:
dict_  = {'1':1,'2':2}

In [4]:
dict_.update({'3':3})

In [5]:
dict_

{'1': 1, '2': 2, '3': 3}

In [1]:
from torch_geometric.data import Data
from torch_geometric.datasets import Planetoid
import os.path as osp
path = osp.join("/data1/zhuowei/datasets/",'Cora')
dataset  = Planetoid(path, 'Cora')

In [12]:
data = dataset[0]

In [13]:
data.cuda()

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [2]:
import torch

In [5]:
torch.arange(5).reshape(-1,1)[:,[0,0]]

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [13]:
a = torch.arange(12, dtype=torch.float).reshape(2,2,-1)
a

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [15]:
torch.mean(a, dim = 1).shape

torch.Size([2, 3])

In [2]:
(1<<5) - 1

31

In [2]:
import torch

l = torch.stack([torch.tensor([1,2]), torch.tensor([3,4])], dim = 0)
l

tensor([[1, 2],
        [3, 4]])

In [3]:
torch.sum(l, dim = -1)

tensor([3, 7])

In [5]:
a = torch.randint(10, size=(3,5,6))
a

tensor([[[1, 0, 7, 4, 7, 7],
         [9, 9, 1, 2, 8, 9],
         [0, 6, 2, 0, 8, 1],
         [8, 2, 4, 8, 5, 6],
         [7, 8, 6, 7, 4, 3]],

        [[9, 6, 8, 4, 6, 4],
         [3, 6, 4, 5, 7, 7],
         [2, 4, 3, 6, 9, 2],
         [9, 4, 0, 3, 4, 8],
         [7, 4, 5, 0, 7, 2]],

        [[8, 1, 7, 1, 9, 5],
         [1, 7, 3, 9, 3, 2],
         [3, 7, 3, 8, 8, 6],
         [3, 5, 3, 5, 5, 9],
         [0, 6, 7, 0, 1, 4]]])

In [6]:
torch.sum(a, dim = 0).shape

torch.Size([5, 6])

In [7]:
a = torch.randint(10,size=(5,6))
b = torch.randint(10,size=(5,6))
c = torch.randint(10,size=(5,6))

In [11]:
k = torch.stack([a,b,c], dim = 0)
k.shape

torch.Size([3, 5, 6])

In [12]:
torch.sum(k,dim=0)

tensor([[12,  6, 10, 14, 21, 16],
        [12, 12, 11, 10, 20, 19],
        [26, 13, 10, 11, 10, 15],
        [19,  6, 13, 10,  5, 14],
        [12, 18, 19,  6, 20, 15]])